# Bluetooth stuff
CONFIG_BT=y
CONFIG_BT_CENTRAL=y         # for NUS client
CONFIG_BT_ZEPHYR_NUS=y      # for NUS
CONFIG_BT_GATT_CLIENT=y     # to discover "mobile chip"
CONFIG_BT_OBSERVER=y        # for scanning
CONFIG_BT_EXT_ADV=y         # for scanning
CONFIG_BT_MAX_CONN=2

# More BT stuff
# Data Length Extension and MTU  
CONFIG_BT_USER_DATA_LEN_UPDATE=y
CONFIG_BT_CTLR_DATA_LENGTH_MAX=251
CONFIG_BT_BUF_ACL_RX_SIZE=251
CONFIG_BT_BUF_ACL_TX_SIZE=251
CONFIG_BT_L2CAP_TX_MTU=247

# Enables the use of k_malloc
CONFIG_HEAP_MEM_POOL_SIZE=4096

# Float support for printk
CONFIG_CBPRINTF_FP_SUPPORT=y

# JSON Library
CONFIG_JSON_LIBRARY=y

# Enable the Floating Point Unit in hardware
CONFIG_FPU=y
CONFIG_FPU_SHARING=y # Save FPU registers on context switch

# Possible Stack error detection in hardware
CONFIG_HW_STACK_PROTECTION=y

# UART Stuff
CONFIG_SERIAL=y
CONFIG_UART_INTERRUPT_DRIVEN=y

# HID keyboard
CONFIG_USB_DEVICE_STACK_NEXT=y
CONFIG_CDC_ACM_SERIAL_INITIALIZE_AT_BOOT=n
CONFIG_USBD_HID_SUPPORT=y

# Power management
CONFIG_REBOOT=y

# CRC tools to ensure validty of packets
CONFIG_CRC=y

# Increases Zephyr Workqueue thread stack
CONFIG_SYSTEM_WORKQUEUE_STACK_SIZE=4096

CONFIG_POSIX_API=y
