default_board := "xiao_ble/nrf52840/sense"

build target:
    west build -o=-j8 -p always -b {{default_board}} -d {{target}}/build {{target}} 

    # Fix clangd warnings
    @sed -i 's/-fno-reorder-functions//g' {{target}}/build/compile_commands.json
    @sed -i 's/-fno-printf-return-value//g' {{target}}/build/compile_commands.json
    @sed -i 's/-mfp16-format=ieee//g' {{target}}/build/compile_commands.json


flash target:
    west flash --runner uf2 -d {{target}}/build

menuconfig target:
    west build -p \
        -b {{default_board}} \
        -d {{target}}/build \
        {{target}} -t menuconfig
